mysql:
  host: "192.168.32.1"
  port: 13316
  username: "root"
  password: "root"
  dbname: "tkshop"

redis:
  host: "192.168.32.1"
  port: 6379
  password: ""

jwt:
  key: "64d4R0yfBgtQARI8VZ6Rc6vII50mIbJp"
